### ISSUE TITLE
Start tagging core

### ISSUE THREAD

**Issue by gvn** [mozilla/webmaker-core#370]
- Start tagging core releases
- Use latest for `android` (some concerns with this...)
- Use locked version for `browser`

cc: @Pomax @k88hudson @thisandagain

**Comment by k88hudson** [comment]
I published core to npm as `webmaker-core` and I've got a PR up for deploying core to npm here https://github.com/mozilla/webmaker-core/pull/375/files

**Comment by gvn** [comment]
We're still not tagging core, but locking to a commit hash seems to be working for `browser`.
